name: Get Github_token
description: Get Github_token to make a release
inputs:
  tag:
    description: Release tag
    required: true
  repository:
    description: The repository (in "owner/repo" format) to look for the tag
    required: true
  auth:
    description: Auth token to use
    required: true

runs:
  using: composite
  steps:
    - name: Get URL
      id: get-url
      shell: bash
      run: |
        release_id=$(curl -sSL -H "Authorization: Bearer ${{ inputs.auth }}" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/${{ inputs.repository }}/releases/tags/${{ inputs.tag }}" | jq -r ".id")
        echo ${{ secrets.GITHUB_TOKEN }} >> $GITHUB_OUTPUT

outputs:
  release-github-token:
    description: Github_token of the release-repo
    value: ${{ secrets.GITHUB_TOKEN }}
